SUP-1700: Agent view output metadata improvements
buildkite/cli pull request #187
Opened 2024-01-16 05:01 UTC by james2791

2024-01-17 03:26 UTC, jradtilbrook commented
I just realised we should probably add a method like `func (Agent) QueueName() string` to go-buildkite to make this simpler. @james2791 could you add a linear ticket to follow up with that

2024-01-17 03:29 UTC, lizrabuya submitted a review, later dismissed
Looks great! 👍

2024-01-17 03:29 UTC, jradtilbrook requested changes
Looks good. But I think making connection state and queue name formatting consistent between commands is a good idea. Currently, `bk agent list` adds colours to those fields that I think you should mimic here

2024-01-18 02:18 UTC, jradtilbrook approved these changes

2024-01-18 02:30 UTC, merged