SUP-1693 Bind "s" to stop agent
buildkite/cli pull request #188
Opened 2024-01-17 04:18 UTC by jradtilbrook

2024-01-17 05:39 UTC, jradtilbrook commented
This is more or less working. There is a UI bug though that seems to not properly update the list (ie I can stop one agent and it gets stopped but the UI removes the wrong agent or it thinks there are still agents in the list)

2024-01-26 08:01 UTC, jradtilbrook commented
For some reason the agent that gets stopped and should be removed from the list of agents is not getting removed. The index in the list that it occupies is set to nil. So the code still thinks the list is X long even though one of the items in that list is nil. I'm still trying to track down where that is being set to nil instead of outright removed

2024-01-26 08:53 UTC, jradtilbrook commented
I've now got this working in tests but I don't think it actually works running it manually; agents never seem to load into the view

2024-01-26 08:55 UTC, jradtilbrook commented
Scratch that, its running forever in CI for some reason, but it passes locally!!

2024-01-29 01:54 UTC, jradtilbrook commented
I've marked this ready for review in case you can spot what the problem is with the tests. Or even if they pass/not pass locally for you could be helpful. Otherwise I think we should mark these tests as skipped for now so we can get this stop functionality merged, even in this state

2024-01-29 03:52 UTC, james2791 commented
Both also pass locally for me 🤔 

Something `HangUpException` in CI?

2024-01-29 05:10 UTC, james2791 requested changes

2024-01-29 05:34 UTC, jradtilbrook commented on internal/agent/list.go
> -	return agentListStyle.Render(m.agentList.View())
Yeah I think its unnecessary

2024-01-29 07:19 UTC, james2791 commented on internal/agent/list.go
> -	return agentListStyle.Render(m.agentList.View())
👍

2024-01-29 07:20 UTC, james2791 approved these changes
:shipit: (3.x rebase/merge proceeding)

2024-01-31 02:03 UTC, james2791 approved these changes

2024-01-31 02:04 UTC, merged