api scopes for all build commands
buildkite/cli pull request #420
Opened 2024-12-15 23:38 UTC by mcncl

## Changes

- Introduce a pre-run check for API scope permissions
- Error where permissions not included with token

2024-12-15 23:50 UTC, lizrabuya reviewed
@mcncl , everything looks good! But is it possible to move the command scope validation into the validation package since it will be reused across different commands?

2025-01-15 08:05 UTC, lizrabuya requested changes
Looks good!

2025-01-15 08:05 UTC, lizrabuya commented on pkg/cmd/build/cancel.go
> +		PreRunE: func(cmd *cobra.Command, args []string) error {
Request to optimise preRun function that appears on several portions in code

2025-01-15 08:44 UTC, mcncl commented on pkg/cmd/build/cancel.go
> +		PreRunE: func(cmd *cobra.Command, args []string) error {
Sure! How would you optimise this code? I'm not overly certain on a way to reduce it further

2025-01-20 23:51 UTC, lizrabuya commented on pkg/cmd/build/cancel.go
> +		PreRunE: func(cmd *cobra.Command, args []string) error {
Oh, the code  to check the scope is fine. But maybe move the implementation in one place (like in pkg/cmd/build/build.go) and refer to it in the other subcommands ?

2025-01-21 01:11 UTC, lizrabuya commented on pkg/cmd/build/cancel.go
> +		PreRunE: func(cmd *cobra.Command, args []string) error {
hi @mcncl , we can implement this feedback in an enhancement.

2025-01-21 01:12 UTC, lizrabuya approved these changes
👍

2025-01-21 01:42 UTC, merged